### ISSUE TITLE
[Upstream] Initial Checklist for 2.3

### ISSUE THREAD

**Issue by ifilonenko** [apache-spark-on-k8s/spark-integration#1]
Running list of tasks to complete to ensure stability in our upstream PRs
--------------
@kimoonkim @foxish @ssuchter 
- [x] Use pre-existing minikube @mccheah 
- [x] Include barebones tests from KubernetesSuite
- [x] Publish MVN artifact for public access
- [x] Modify RiseLabsCLI and Pepperdata Jenkins to point to that public artifact

**Comment by foxish** [comment]
Thanks for filing the issue.
Step 2 is for https://github.com/apache-spark-on-k8s/spark-integration correct?

**Comment by ifilonenko** [comment]
Yes this issue is exclusively for this repo
